[build]
  command = "git fetch https://github.com/jkremser/k8gb gh-pages:gh-pages && git checkout gh-pages && make build"
  publish = "_site/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"
