[build]
  command = "git remote add -f -t gh-pages origin https://github.com/jkremser/k8gb && git checkout gh-pages && make build"
  publish = "_site/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"
