[build]
  command = "git remote -v && git fetch origin gh-pages && git checkout origin/gh-pages && make build"
  publish = "_site/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"
