apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy":  hook-succeeded
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - delete
