apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hook-role-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy":  hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hook-role
subjects:
- kind: ServiceAccount
  name: hook-sa
  namespace: {{ .Release.Namespace }}
