name: KubeLinter

on:
  push:
    paths:
      - 'chart/k8gb/**'
  pull_request:
    branches:
      - master
    paths:
      - 'chart/k8gb/**'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan repo
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: chart/k8gb
          version: 0.2.5
      - name: Fail if no chart was found
        run: |
          grep --silent 'Warning: no valid objects found' kubelinter.log && exit 1 || exit 0
