name: Terratest

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'

jobs:
  terratest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.9"

      - name: Build artifacts
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create 1st k3s Cluster
        uses: AbsaOSS/k3d-action@v1.5.0
        with:
          cluster-name: "test-gslb1"
          args: -c k3d/test-gslb1.yaml

      - name: Create 2nd k3s Cluster
        uses: AbsaOSS/k3d-action@v1.5.0
        with:
          cluster-name: "test-gslb2"
          args: -c k3d/test-gslb2.yaml

      - name: Create 3rd k3s Cluster
        uses: AbsaOSS/k3d-action@v1.5.0
        with:
          cluster-name: "test-gslb3"
          args: -c k3d/test-gslb3.yaml

      - name: K8GB deployment
        run: |
          make deploy-test-version list-running-pods CLUSTERS_NUMBER=3
          echo "Cluster 1 (eu):"
          kubectl get no -owide --context=k3d-test-gslb1
          echo "Cluster 2 (us):"
          kubectl get no -owide --context=k3d-test-gslb2
          echo "Cluster 3 (cz):"
          kubectl get no -owide --context=k3d-test-gslb3

      - name: Terratest (round robin for 3 clusters)
        run: |
          cd terratest/test/
          go mod download
          go get -u github.com/rakyll/gotest
          gotest -v -timeout 15m -parallel=12 ./3clusters

      - name: Delete 3rd k3s Cluster
        run: | 
          k3d cluster delete test-gslb3
          make deploy-test-version list-running-pods CLUSTERS_NUMBER=2
          echo "Cluster 1 (eu):"
          kubectl get no -owide --context=k3d-test-gslb1
          echo "Cluster 2 (us):"
          kubectl get no -owide --context=k3d-test-gslb2

      - name: Terratest (2 clusters)
        run: |
          cd terratest/test/
          go mod download
          gotest -v -timeout 15m -parallel=12 ./2clusters
